Statinis reviews
front-end-by-rimantas/14-grupe-portfolio-netlify pull request #58
Opened 2020-04-16 10:46 UTC by Belendor

2020-04-16 10:49 UTC, JustinaKlim requested changes
Greiciausiai bus conflict home-page.css, gal perkeltum i 14 eilute?

2020-04-16 10:53 UTC, Belendor commented
> Greiciausiai bus conflict home-page.css, gal perkeltum i 14 eilute?
Tai jei ir bus greit isspresim per cia, nera realiai skirtumo :)

2020-04-16 10:56 UTC, JustinaKlim submitted a review, later dismissed

2020-04-17 08:02 UTC, JustinaKlim approved these changes

2020-04-17 08:05 UTC, merged